version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn build
  test:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: yarn
      - run: ./test-ci-unit.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
